ContactApplication/urls.py
from django.urls import path
from . import views
from .views import mentorListView, repListView

app_name = 'ContactApplication'
urlpatterns = [
    path('', views.home, name = 'home'),
    
    path('mentors', mentorListView.as_view(), name = 'mentors'),
    path('reps', repListView.as_view(), name = 'reps'),
]

DevelopmentProject/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from users import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ContactApplication.urls')),
    path('messaging/', include('messaging.urls')),
    path('forums/', include('forum.urls') ),

    path('register', user_views.register, name = 'register'),
    path('login', auth_views.LoginView.as_view(template_name = 'users/login.html'), name = 'login'),
    path('logout', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name='logout'),

    #Different profile creation pages
    path('studentprofilecreate', user_views.studentprofilecreate, name = 'studentprofilecreate'),
    path('mentorprofilecreate', user_views.mentorprofilecreate, name = 'mentorprofilecreate'),
    path('studentrepprofilecreate', user_views.studentrepprofilecreate, name = 'studentrepprofilecreate'),
    path('profileselector', views.profileselection, name = 'profileselector'),

    #Profile/update pages
    path('studentprofile', user_views.studentprofile, name = 'studentprofile'),
    path('mentorprofile', user_views.mentorprofile, name = 'mentorprofile'),
    path('studentrepprofile', user_views.studentrepprofile, name = 'studentrepprofile'),

    path('mentorrefgen', user_views.MentorNumGen, name = 'mentornumgen'),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

forum/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView
from .views import CommentCreateView, CommentDeleteView

app_name = 'forums'

urlpatterns = [
    path('posts', PostListView.as_view(), name = 'posts'),
    path('post/<int:pk>', PostDetailView.as_view(), name = 'post-detail'),
    path('post/new', PostCreateView.as_view(), name = 'post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name = 'post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name = 'post-delete'),
    path('post/<int:pk>/comment/', CommentCreateView.as_view(), name='comment-create'),
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment-delete'),
]

messaging/urls.py
from django.urls import path
from . import views

app_name = 'messaging'

urlpatterns = [
    path('send_message/<str:recipient_username>/', views.send_message, name='send_message'),
    path('inbox/', views.inbox, name='inbox'),
    path('reply_message/<int:message_id>/', views.reply_message, name='reply_message'),
]

ContactApplication/views.py
from django.shortcuts import render
from users.models import MentorProfile, StudentRepProfile
from django.views.generic import ListView

def home(request):
    return render(request, 'ContactApplication/home.html', {'title':'Welcome'})

def mentors(request):

        mentor_list = {'mentors': MentorProfile.objects.all(), 'title': 'Here are our mentors'}
        return render(request, 'ContactApplication/mentors.html', {'mentorprofiles': mentor_list})

class mentorListView(ListView):
    model = MentorProfile
    template_name = 'ContactApplication/mentors.html'
    context_object_name = 'mentorprofiles'
    ordering = ['AreaOfStudy']
    paginate_by = 6
    
def studentreps(request):
     
     rep_list = {'studentreps': StudentRepProfile.objects.all(), 'title': 'These are the student reps working with us'}
     return render(request, 'ContactApplication/reps.html', {'studentrepprofiles': rep_list})

class repListView(ListView):
     model = StudentRepProfile
     template_name = 'ContactApplication/reps.html'
     context_object_name = 'studentrepprofiles'
     ordering = ['AreaOfStudy']
     paginate_by = 6

ContactApplication/templates/ContactApplication/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}" />
    <title>Shu contact - {{title}}</title>


</head>

<body>
    {% if user.mentorprofile %}
        <div class="sidenav">
            <a href="#">null</a>
            <a href="{% url 'messaging:inbox' %}">Messages</a>
            <a href="{% url 'forums:posts' %}">Forums</a>
        </div>
    {% elif user.studentprofile %}
        <div class="sidenav">
            <a href="#">null</a>
            <a href="{% url 'messaging:inbox' %}">Messages</a>
            <a href="{% url 'forums:posts' %}">Forums</a>
        </div>
    {% elif user.studentrepprofile %}
        <div class="sidenav">
            <a href="#">null</a>
            <a href="{% url 'messaging:inbox' %}">Messages</a>
            <a href="{% url 'forums:posts' %}">Forums</a>
        </div>
    {% else %}
    {% endif %}

    <div class="container">
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
                <div class="container">
                <a class="navbar-brand mr-4" href="{% url 'ContactApplication:home' %}">Shu Contact</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{% url 'ContactApplication:home' %}">Home</a>
                        <a class="nav-item nav-link" href="{% url 'ContactApplication:reps' %}">Student Reps</a>
                        <a class="nav-item nav-link" href="{% url 'ContactApplication:mentors' %}">Mentors</a>
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">

                        {% if user.is_authenticated and user.studentprofile.StudentNumber %}
                            <a class="nav-item nav-link" href="{% url 'studentprofile' %}">Student Profile</a>
                            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>

                        {% elif user.is_authenticated and user.mentorprofile.MentorRefNumber %}
                            <a class="nav-item nav-link" href="{% url 'mentorprofile' %}">Mentor Profile</a>
                            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>

                        {% elif user.is_authenticated and user.studentrepprofile.StudentNumber %}
                            <a class="nav-item nav-link" href="{% url 'studentrepprofile' %}">Student Rep Profile</a>
                            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>

                        {% elif user.is_authenticated %}
                            <a class="nav-item nav-link" href="{% url 'profileselector' %}">Create profile</a>
                            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>

                        {% else %}
                            <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                            <a class="nav-item nav-link" href="{% url 'register' %}">Register as user</a>
                        {% endif %}
                       </div>
                </div>
                </div>
            </nav>
        </header>
        <div class="row">
            <div class="col-md-8">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{message.tags}}">{{ message }}</div>
                {% endfor %}
            {% endif %}

            </div>
        </div>
        {% block content %}{% endblock %}
    </div>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

ContactApplication/templates/ContactApplication/home.html
{% extends "ContactApplication/base.html" %}
{% block content %}
    <h1>Welcome to Shu Contact</h1>

    <div class="cardleft">
        <h2>The Goal</h2>
        <p>Have you ever had issues with contacting a lecturer? Had issues knowing who your student reps are?
        </br>This website aims to help solve this issue by providing a centralised location to find lecturers.
        </br>Shu Contact allows you to contact lecturers, student reps and other students, as well as create group messages.
        </br>In order to use Shu Contact you need an account, in order to create an account visit the registration page.
        </br>Once you have created an account, you need to register for a profile, you can have a student, student rep or mentor profile.
        </p>
    </div>
    <div class="paddingelem"></div>
    <div class="cardleft">
        <h2>Mentors</h2>
        <p>Having a mentor profile means you will be shown to users on the profile page, meaning users will be able to find you.
        </br>In order to create a mentor profile you will need a reference number, you will need to obtain this from a current mentor.
        </br>To sign up for a mentor profile you will first need a standard account. If you do not have this press register.
        </br>After you have a standard account you need to press create a profile, this will be in the top right of your screen.
        </br>Once you have a mentor proile your profile will be shown on the mentors page, this will allow people to see your basic details.
        </p>
    </div>
    <div class="paddingelem"></div>
    <div class="cardleft">
        <h2>Student Reps</h2>
        <p>Student reps can create a student rep profile, this will allow them to be shown off on the appropriate student rep page.
        </br>By being on this page you acknowledge that people will contact you, meaning that you will receive messages. 
        </br>While there is not much difference between having a student and student rep profile, being displayed makes you a main point of contact.
        </br>Before acquiring a student rep account you will need a standard account. If you do not have one press register.
        </br>Once you have a standard account you will need to press create profile which will take you through profile creation.
        </p>
    </div>
    <div class="paddingelem"></div>
    <div class="cardleft">
        <h2>Students</h2>
        <p>As a student you can contact mentors and student reps, the difference between a student profile and other profiles is that nobody can contact you first.
        </br>This website aims to make it easier to contact them, you'll be able to directly message student reps and lecturers here!
        </br>First you will need to create an account, press the register button in order to create an account.
        </br>Once you have an account you'll need to create a student account, press create profile in order to do this.
        </br>Once you do this you can message a student rep/mentor by pressing contact on their profiles.
        </p>
    </div>
{% endblock content %}

ContactApplication/templates/ContactApplication/mentors.html
{% extends "ContactApplication/base.html" %}
{% block content %}
    <h1>Here are the mentors working with us!</h1>
    {% for mentorprofile in mentorprofiles %}
        <div class="column">
            <div class="card">
                <div style="text-align: center;">
                    <img class="rounded-circle" src="{{mentorprofile.Image.url}}", width="270", height="270">
                </div>    
                <h1>{{ mentorprofile.user.first_name }} {{ mentorprofile.user.last_name }}</h1>
                <h2>Mentor</h2>
                <p class="title"> Specialises in {{ mentorprofile.AreaOfStudy }}</p>
                <p>{{ mentorprofile.Description }}</p>
                <div class="bottomcard">
                    <div class="article-metadata">
                    </div>

                    <p class="muted">Email address:</br> {{ mentorprofile.user.email }}</p>
                    <a href="{% url 'messaging:send_message' recipient_username=mentorprofile.user.username %}">
                        <button>Contact</button>
                    </a>
                </div>
            </div>
        </div>
            
    {% endfor %}
    <div class="columnend">
        {% if is_paginated %}
        {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{page_obj.previous_page_number}}">Previous</a>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
        <a class="btn btn-info mb-4" href="?page={{num}}">{{num}}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <a class="btn btn-outline-info mb-4" href="?page={{num}}">{{num}}</a>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{page_obj.next_page_number}}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{page_obj.paginator.num_pages}}">Last</a>
        {% endif %}
        {% endif %}
    </div>
{% endblock content %}

ContactApplication/templates/ContactApplication/reps.html
{% extends "ContactApplication/base.html" %}
{% block content %}
    <h1>These are your student reps! </h1>
    {% for studentrepprofile in studentrepprofiles %}
    <div class="column">
        <div class="card">
            <div style="text-align: center;">
                <img class="rounded-circle" src="{{studentrepprofile.Image.url}}", width="270", height="270">
            </div>  
            <h1>{{ studentrepprofile.user.first_name }} {{ studentrepprofile.user.last_name }}</h1>
            <h2>Student Rep</h2>
            <p class="title"> Studies {{ studentrepprofile.AreaOfStudy }}</p>
            <p>{{ studentrepprofile.Description }}</p>
            <div class="bottomcard">
                <div class="article-metadata">
                </div>

                <p class="muted">Student number:</br> {{ studentrepprofile.StudentNumber }}</p>
                <a href="{% url 'messaging:send_message' recipient_username=studentrepprofile.user.username %}">
                    <button>Contact</button>
                </a>
            </div>
        </div>
    </div>
        
{% endfor %}
<div class="columnend">
    {% if is_paginated %}
    {% if page_obj.has_previous %}
    <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
    <a class="btn btn-outline-info mb-4" href="?page={{page_obj.previous_page_number}}">Previous</a>
    {% endif %}
    {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
    <a class="btn btn-info mb-4" href="?page={{num}}">{{num}}</a>
    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
    <a class="btn btn-outline-info mb-4" href="?page={{num}}">{{num}}</a>
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <a class="btn btn-outline-info mb-4" href="?page={{page_obj.next_page_number}}">Next</a>
    <a class="btn btn-outline-info mb-4" href="?page={{page_obj.paginator.num_pages}}">Last</a>
    {% endif %}
    {% endif %}
</div>
{% endblock content %}