DevelopmentProject/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from users import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ContactApplication.urls')),
    path('messaging/', include('messaging.urls')),
    path('forums/', include('forum.urls') ),

    path('register', user_views.register, name = 'register'),
    path('login', auth_views.LoginView.as_view(template_name = 'users/login.html'), name = 'login'),
    path('logout', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name='logout'),

    #Different profile creation pages
    path('studentprofilecreate', user_views.studentprofilecreate, name = 'studentprofilecreate'),
    path('mentorprofilecreate', user_views.mentorprofilecreate, name = 'mentorprofilecreate'),
    path('studentrepprofilecreate', user_views.studentrepprofilecreate, name = 'studentrepprofilecreate'),
    path('profileselector', views.profileselection, name = 'profileselector'),

    #Profile/update pages
    path('studentprofile', user_views.studentprofile, name = 'studentprofile'),
    path('mentorprofile', user_views.mentorprofile, name = 'mentorprofile'),
    path('studentrepprofile', user_views.studentrepprofile, name = 'studentrepprofile'),

    path('mentorrefgen', user_views.MentorNumGen, name = 'mentornumgen'),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

forum/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView
from .views import CommentCreateView, CommentDeleteView

app_name = 'forums'

urlpatterns = [
    path('posts', PostListView.as_view(), name = 'posts'),
    path('post/<int:pk>', PostDetailView.as_view(), name = 'post-detail'),
    path('post/new', PostCreateView.as_view(), name = 'post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name = 'post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name = 'post-delete'),
    path('post/<int:pk>/comment/', CommentCreateView.as_view(), name='comment-create'),
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment-delete'),
]

forum/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

#This is how the posts are stored
class Post(models.Model):
    #This gives the user the option between the 2 types of post
    typeofpost = models.CharField(max_length=50 , choices = [('Problem', 'Problem'), ('Discussion', 'Discussion')])
    title = models.CharField(max_length=40)
    #This makes sure that a user is attached to a post
    user = models.ForeignKey(User, related_name= 'Post', on_delete=models.DO_NOTHING)
    description = models.TextField()
    timesubmitted = models.DateTimeField(default= timezone.now)

    def __str__(self):
        return f'{self.title}'
    
    #This makes sure that a user will see their post after making it
    def get_absolute_url(self):
        return reverse('forums:post-detail', kwargs = {'pk' : self.pk})
    
#This handles the comments, which are directly associated with posts
class Comment(models.Model):
    #This is what attaches comments to the post
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    content = models.TextField()
    #This is used to track the user who posts the comment
    usercomment = models.ForeignKey(User, related_name= 'Comment', on_delete=models.DO_NOTHING)
    timesent = models.DateTimeField(default= timezone.now)

forum/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Post, Comment

class PostForm(forms.ModelForm):
    typeofpost = forms.ChoiceField(choices=[('Problem', 'Problem'), ('Discussion', 'Discussion')], label='The type of post you want to make.')
    title = forms.CharField(label='The title of your post.')
    description = forms.CharField(label='The content of your post', max_length=600)
    class Meta: 
        model = Post
        fields = ['typeofpost', 'title', 'description']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'placeholder': 'Write your comment here...', 'rows': 4}),
        }

forum/views.py
from django.shortcuts import render, redirect
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.core.paginator import Paginator
from django.core.paginator import UnorderedObjectListWarning
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
import warnings

warnings.filterwarnings('ignore', 'Pagination may yield inconsistent results with an unordered object_list', UnorderedObjectListWarning)

def posts(request):
    forum_posts = {'posts': Post.objects.all(), 'title': 'Forum posts'}
    return render(request, 'forum/forum.html', forum_posts)


class PostListView(ListView):
    model = Post
    template_name = 'forum/forum.html'
    context_object_name = 'posts'
    ordering = ['-timesubmitted']
    paginate_by = 5

class PostDetailView(DetailView):
    model = Post
    template_name = 'forum/post_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        comments = post.comments.all()  

        paginator = Paginator(comments, 10)  
        page_number = self.request.GET.get('page')
        comment_page = paginator.get_page(page_number)

        context['comment_form'] = CommentForm() 
        context['comment_page'] = comment_page
        return context

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostForm

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.user

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/forums/posts'

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.user

class CommentCreateView(CreateView):
    template_name = 'forum/post_detail.html'
    form_class = CommentForm

    def form_valid(self, form):
        post_id = self.kwargs['pk']  
        comment = form.save(commit=False)
        comment.post_id = post_id  
        comment.usercomment = self.request.user  
        comment.save()
        return redirect('forums:post-detail', pk=post_id)
    
class CommentDeleteView(DeleteView):
    model = Comment
    template_name = 'forum/comment_confirm_delete.html'

    def get_success_url(self):
        post = self.object.post
        return reverse_lazy('forums:post-detail', kwargs={'pk': post.pk})

forum/templates/forum/forum.html
{% extends "ContactApplication/base.html" %}
{% block content %}
<h1>These are the posts made by this websites' users!</h1>
<p>There are 2 different post types, problems and discussions. Problems need solutions, so if you see a problem post make sure to help someone out.</p>
<p>The other type of post is a discussion, these posts will usually be for people who want to talk about something but don't necessarily need solutions.</p>

<div class="make-post-button" style="margin-left: 15px;">
    <a href="{% url 'forums:post-create' %}">
        <button>Make Post</button>
    </a>
</div>
</br>

{% for post in posts %}
    <div class="cardtext">
        <p class="text-content">Posted at {{ post.timesubmitted }}<span class="text-content" style="float: right;">This post was made by {{ post.user }}</span>
        {% if post.user.mentorprofile %}
            <p class="text-content">This user is a mentor</p>
            {% elif post.user.studentrepprofile %}
            <p class="text-content">This user is a student rep</p>
            {% elif post.user.studentprofile %}
            <p class="text-content">This user is a student</p>
        {% endif %}
        </p>
        <h2>{{ post.title }}</h2>
        <h5>{{ post.typeofpost }} </h5>
        <div class="article-metadata"></div>
        <p>{{ post.description }}</p>
        <a href="{% url 'forums:post-detail' post.id %}">
            <button>View post</button>
        </a>
    </div>
{% endfor %}

    <div class="columnend">
        {% if is_paginated %}
        {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{page_obj.previous_page_number}}">Previous</a>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
        <a class="btn btn-info mb-4" href="?page={{num}}">{{num}}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <a class="btn btn-outline-info mb-4" href="?page={{num}}">{{num}}</a>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{page_obj.next_page_number}}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{page_obj.paginator.num_pages}}">Last</a>
        {% endif %}
        {% endif %}
    </div>

 <style>
    button {
        width: 20%;
    }
    .cardtext {
        height: 350px;
        max-height: 350px;
    }
    .make-post-button {
            margin-top: 20px; 
        }
</style>
{% endblock content %}

forum/templates/forum/post_confirm_delete.html
{% extends "ContactApplication/base.html" %}
{% block content %}
<div class="row">
    <div class="cardtext">
        <!--This shows the post off-->
        <p class="text-content">Posted at {{ post.timesubmitted }}<span class="text-content" style="float: right;">This post was made by {{ post.user }}</span></p>
        <h2>{{ post.title }}</h2>
        <h5>This post is specified to be a {{ post.typeofpost }} </h5>
        <div class="article-metadata"></div>
        <p>{{ post.description }}</p>

        <!--This deletes the post when the user presses the delete button-->
        <form method="POST">
            <!--This token checks that the user is one submitting the request-->
            {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="button">Delete forum post?</legend>
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-danger" type="submit">Delete</button>
                </div>
        </form>

    </div>

        
            
</div>

<style>
    /*This styles the cardtext element specifically for this page*/
    .cardtext {
        height: 360px;
        max-height: 360px;
    }
</style>
{% endblock content %}

forum/templates/forum/post_detail.html
{% extends "ContactApplication/base.html" %}
{% block content %}
<div class="cardtext">
    <p class="text-content">Posted at {{ post.timesubmitted }}
    <span class="text-content" style="float: right;">This post was made by {{ post.user }}</span></p>
        {% if post.user.mentorprofile %}
            <p class="text-content">This user is a mentor</p>
        {% elif post.user.studentrepprofile %}
            <p class="text-content">This user is a student rep</p>
        {% elif post.user.studentprofile %}
            <p class="text-content">This user is a student</p>
        {% endif %}
    <h2>{{ post.title }}</h2>
    <h5>{{ post.typeofpost }}</h5>
    <div class="article-metadata"></div>
    <p>{{ post.description }}</p>

    {% if object.user == user %}
        <a href="{% url 'forums:post-update' object.id %}">
            <button>Update post</button>
        </a>

        <a href="{% url 'forums:post-delete' object.id %}">
            <button>Delete post</button>
        </a>
    {% endif %}


</div>

<h2>Comments:</h2>

{% if comment_page.has_other_pages %}
    <div class="comment-pagination">
        {% if comment_page.has_previous %}
            <a href="?page={{ comment_page.previous_page_number }}">Previous</a>
        {% endif %}
        {% if comment_page.has_next %}
            <a href="?page={{ comment_page.next_page_number }}">Next</a>
        {% endif %}
    </div>
{% endif %}
</br>

{% if comment_page.object_list %}
    {% for comment in comment_page.object_list %}
        <div class="comment">
            <div class="comment-content">
                <p>{{ comment.content }}</p>
            </div>
            <div class="comment-metadata">
                <p style="display: inline-block; margin-right: 10px;">Posted by {{ comment.usercomment }} at {{ comment.timesent }}</p>
                {% if comment.usercomment.mentorprofile %}
                    <p class="text-content">This user is a mentor</p>
                {% elif comment.usercomment.studentrepprofile %}
                    <p class="text-content">This user is a student rep</p>
                {% elif comment.usercomment.studentprofile %}
                    <p class="text-content">This user is a student</p>
                {% endif %}
                {% if request.user == comment.usercomment %}
                    <form method="post" action="{% url 'forums:comment-delete' comment.id %}">
                        {% csrf_token %}
                        <button type="submit" style="display: none;">Delete</button>  
                        <img src="/media/Bin.png" alt="Delete" onclick="this.previousElementSibling.click()" style="cursor: pointer; width: 20px; height: 20px;">
                    </form>
                </br>
                {% endif %}
            </div>
            <div class="article-metadata"></div>
            <div style="clear: both;"></div> 
        </div>
    {% endfor %}
{% else %}
    <p>No comments yet. Be the first to comment!</p>
{% endif %}

{% if user.is_authenticated %}
    <h3>Add a Comment:</h3>
    <form method="post" action="{% url 'forums:comment-create' post.id %}">
        {% csrf_token %}

        <input type="hidden" name="post_id" value="{{ post.id }}">
        <textarea id="comment-content" name="content" placeholder="Write your comment here..." required cols="50" rows="6" maxlength="500"></textarea>
        <p id="char-count">Characters remaining: 500</p>
    </br>
        <button type="submit">Submit Comment</button>
    </form>
{% else %}
    <p>Please <a href="{% url 'login' %}">log in</a> to leave a comment.</p>
{% endif %}

<style>
    button {
        width: 30%;
    }
    .cardtext {
        height: 350px;
        max-height: 350px;
    }
    .comment {
        margin-bottom: 20px;
    }
    .comment-metadata {
        font-style: italic;
        font-size: 0.8em;
    }
</style>

<script>
    document.addEventListener("DOMContentLoaded", function() {
    var textarea = document.getElementById("comment-content");
    console.log(textarea); 
    if (textarea) {
        textarea.addEventListener("input", function() {
            var maxLength = 500;
            var currentLength = this.value.length;
            var remainingLength = maxLength - currentLength;
            document.getElementById("char-count").textContent = "Characters remaining: " + remainingLength;
        });
    }
});
</script>
{% endblock content %}

forum/templates/forum/post_form.html
{% extends "ContactApplication/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        <div class="content-section">
            <form method="POST">
            {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Forum post creator/updator</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <h6>By making a forum post your name will be displayed.</h6>
                    <button class="btn btn-outline-info" type="submit">Post</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}